[[constraint]]
  branch = "master"
  name = "github.com/kolide/osquery-go"

[[constraint]]
  branch = "master"
  name = "github.com/kolide/updater"

[[constraint]]
  branch = "master"
  name = "github.com/kolide/kit"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/errors"

[[override]]
  name = "git.apache.org/thrift.git"
  source = "git@github.com:kolide/thrift.git"
  branch = "master"
