version: 2.1

orbs:
  windows: circleci/windows@2.4.0
  go: circleci/go@1.1.0

jobs:
  build-and-test-linux:
    executor:
      name: go/default
      tag: '1.14'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run: make deps
      - run: make -j lint
      - run: make -j {linux,windows}-xp-{launcher,extension,grpc-extension} package-builder
      - run: make test
  build-and-test-windows:
    executor:
      name: windows/default
      size: "medium"
    steps:
      - checkout
      - run: choco install --no-progress make
      - run: make deps
      - run: make -j all
      - run: make test

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build-and-test-linux
      - build-and-test-windows
