workflows:
  version: 2
  build:
    jobs:
      - build-go1.10.1

version: 2
jobs:
  build-go1.11:
    docker:
        - image: golang:1.11
    working_directory: /go/src/github.com/kolide/kit
    steps: &steps
      - checkout
      - run: make deps
      - run: make test
      - run: make extension
      - run: make launcher

workflows:
  version: 2
  build:
    jobs:
      - build-go1.11
