version: 2
jobs:
  build-go1.8:
    docker:
        - image: kolide/launcher-builder:1.8
    working_directory: /go/src/github.com/kolide/launcher
    steps: &steps
      - checkout
      - restore_cache:
          keys:
            - vendor-cache-{{ .Branch }}-{{ checksum "glide.lock" }}
            - vendor-cache-{{ .Branch }}
            - vendor-cache
      - run: UNVALIDATED=true make deps
      - save_cache:
          key: vendor-cache-{{ .Branch }}-{{ checksum "glide.lock" }}
          paths:
            - vendor
      - save_cache:
          key: vendor-cache-{{ .Branch }}
          paths:
            - vendor
      - save_cache:
          key: vendor-cache
          paths:
            - vendor

      - run: UNVALIDATED=true make test
      - run: make extension
      - run: make launcher

  build-go1.9:
    docker:
        - image: kolide/launcher-builder:1.9
    working_directory: /go/src/github.com/kolide/launcher
    steps: *steps

workflows:
  version: 2
  build:
    jobs:
      - build-go1.8
      - build-go1.9
