version: 2
jobs:
  build-go1.10.1:
    docker:
        - image: kolide/launcher-builder:1.10.1
    working_directory: /go/src/github.com/kolide/launcher
    steps: &steps
      - checkout
      - restore_cache:
          keys:
            - vendor-cache-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
            - vendor-cache-{{ .Branch }}
            - vendor-cache
      - run: make deps
      - save_cache:
          key: vendor-cache-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - save_cache:
          key: vendor-cache-{{ .Branch }}
          paths:
            - vendor
      - save_cache:
          key: vendor-cache
          paths:
            - vendor

      - run: make test
      - run: make extension
      - run: make launcher

workflows:
  version: 2
  build:
    jobs:
      - build-go1.10.1
