name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
      - master
  pull_request:
jobs:
  golangci:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: adjust path for generation
        run: echo "${HOME}/go/bin" >> $GITHUB_PATH

      - name: adjust path for generation (windows)
        if: matrix.os == 'windows-latest'
        run: echo "${HOME}\go\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - run: make deps

      # Work around https://github.com/golangci/golangci-lint-action/issues/362
      - name: don't process annotations
        run:  echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"


      # Getting this to work outside a normal build is quite
      # cumbersome. golangci/golangci-lint-action attempts to install
      # go, and use the module cache. In a way that _assumes_ no go
      # commands have been run in the workspace. But, this is
      # fundamentally incompatible with our needing to to generate
      # code before linting. Thus the various skip- commands.  See
      # https://github.com/golangci/golangci-lint-action/issues/244
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42
          skip-pkg-cache: true
